using System.Collections.Generic;

namespace BestPlaylists.Common
{
    public static class DbConstants
    {
        public const string Admin1Name = "Deyan";
        public const string Admin1FirstName = "Deyan";
        public const string Admin1LastName = "Todorov";
        public const string Admin1Email = "deyan@gmail.com";
        public const string Admin1Pass = "123123";

        public const string Editor1Name = "Editor";
        public const string Editor1FirstName = "Editor";
        public const string Editor1LastName = "Editor";
        public const string Editor1Email = "editor@gmail.com";
        public const string Editor1Pass = "123123";

        public const string RoleAdmin = "Admin";
        public const string RoleEditor = "Editor";
        
        public static List<string> musicGenres = new List<string>()
        {
            "Alternative",
            "Art Punk",
            "Alternative Rock",
            "College Rock",
            "Experimental Rock",
            "Goth / Gothic Rock",
            "Grunge",
            "Hardcore Punk",
            "Hard Rock",
            "Indie Rock",
            "Lo-fi(hat tip to Ben Vee Bedlamite)",
            "New Wave",
            "Progressive Rock",
            "Punk",
            "Shoegaze(with thx to Jackie Herrera)",
            "Steampunk(with thx to Christopher Schaeffer)",
            "Anime",
            "Blues",
            "Acoustic Blues",
            "Chicago Blues",
            "Classic Blues",
            "Contemporary Blues",
            "Country Blues",
            "Delta Blues",
            "Electric Blues",
            "Children’s Music",
            "Lullabies",
            "Sing-Along",
            "Stories",
            "Classical",
            "Avant-Garde",
            "Baroque",
            "Chamber Music",
            "Chant",
            "Choral",
            "Classical Crossover",
            "Early Music",
            "High Classical",
            "Impressionist",
            "Medieval",
            "Minimalism",
            "Modern Composition",
            "Opera",
            "Orchestral",
            "Renaissance",
            "Romantic",
            "Wedding Music",
            "Comedy",
            "Novelty",
            "Standup Comedy",
            "Vaudeville(cheers Ben Vee Bedlamite)",
            "Commercial(thank you Sheldon Reynolds)",
            "Jingles",
            "TV Themes",
            "Country",
            "Alternative Country",
            "Americana",
            "Bluegrass",
            "Contemporary Bluegrass",
            "Contemporary Country",
            "Country Gospel",
            "Country Pop(thanks Sarah Johnson)",
            "Honky Tonk",
            "Outlaw Country",
            "Traditional Bluegrass",
            "Traditional Country",
            "Urban Cowboy",
            "Dance(EMD – Electronic Dance Music – see Electronic below – with thx to Eric Shaffer-Whiting)",
            "Club / Club Dance(thx Luke Allfree)",
            "Breakbeat",
            "Brostep(cheers Tom Berckley)",
            "Deep House(cheers Venus Pang)",
            "Dubstep",
            "Electro House(thx Luke Allfree)",
            "Exercise",
            "Garage",
            "Glitch Hop(cheers Tom Berckley)",
            "Hardcore",
            "Hard Dance",
            "Hi-NRG / Eurodance",
            "House",
            "Jackin House(with thx to Jermaine Benjamin Dale Bruce)",
            "Jungle / Drum’n’bass",
            "Regstep(thanks to ‘Melia G)",
            "Techno",
            "Trance",
            "Trap(thx Luke Allfree)",
            "Disney",
            "Easy Listening",
            "Bop",
            "Lounge",
            "Swing",
            "Electronic",
            "8bit – aka 8-bit, Bitpop and Chiptune – (thx Marcel Borchert)",
            "Ambient",
            "Bassline(thx Leon Oliver)",
            "Chiptune(kudos to Dominik Landahl)",
            "Crunk(with thx to Jillian Edwards)",
            "Downtempo",
            "Drum & Bass(thx Luke Allfree)",
            "Electro",
            "Electro-swing(thank you Daniel Forthofer)",
            "Electronica",
            "Electronic Rock",
            "Hardstyle(kudos to Dominik Landahl)",
            "IDM/Experimental",
            "Industrial",
            "Trip Hop(thank you Michael Tait Tafoya)",
            "Enka",
            "French Pop",
            "German Folk",
            "German Pop",
            "Fitness & Workout",
            "Hip-Hop/Rap",
            "Alternative Rap",
            "Bounce",
            "Dirty South",
            "East Coast Rap",
            "Gangsta Rap",
            "Hardcore Rap",
            "Hip-Hop",
            "Latin Rap",
            "Old School Rap",
            "Rap",
            "Turntablism(thank you Luke Allfree)",
            "Underground Rap",
            "West Coast Rap",
            "Holiday",
            "Chanukah",
            "Christmas",
            "Christmas: Children’s",
            "Christmas: Classic",
            "Christmas: Classical",
            "Christmas: Jazz",
            "Christmas: Modern",
            "Christmas: Pop",
            "Christmas: R&B",
            "Christmas: Religious",
            "Christmas: Rock",
            "Easter",
            "Halloween",
            "Holiday: Other",
            "Thanksgiving",
            "Indie Pop",
            "Industrial",
            "Inspirational – Christian & Gospel",
            "CCM",
            "Christian Metal",
            "Christian Pop",
            "Christian Rap",
            "Christian Rock",
            "Classic Christian",
            "Contemporary Gospel",
            "Gospel",
            "Christian & Gospel",
            "Praise & Worship",
            "Qawwali(with thx to Jillian Edwards)",
            "Southern Gospel",
            "Traditional Gospel",
            "Instrumental",
            "March(Marching Band)",
            "J-Pop",
            "J-Rock",
            "J-Synth",
            "J-Ska",
            "J-Punk",
            "Jazz",
            "Acid Jazz(with thx to Hunter Nelson)",
            "Avant-Garde Jazz",
            "Bebop(thx Mwinogo1)",
            "Big Band",
            "Blue Note(with thx to Jillian Edwards)",
            "Contemporary Jazz",
            "Cool",
            "Crossover Jazz",
            "Dixieland",
            "Ethio-jazz(with thx to Jillian Edwards)",
            "Fusion",
            "Gypsy Jazz(kudos to Mike Tait Tafoya)",
            "Hard Bop",
            "Latin Jazz",
            "Mainstream Jazz",
            "Ragtime",
            "Smooth Jazz",
            "Trad Jazz",
            "K-Pop",
            "Karaoke",
            "Kayokyoku",
            "Latin",
            "Alternativo & Rock Latino",
            "Argentine tango(gracias P. Moth & Sandra Sanders)",
            "Baladas y Boleros",
            "Bossa Nova(with thx to Marcos José Sant’Anna Magalhães & Alex Ede for the reclassification)",
            "Brazilian",
            "Contemporary Latin",
            "Flamenco / Spanish Flamenco(thank you Michael Tait Tafoya & Sandra Sanders)",
            "Latin Jazz",
            "Nuevo Flamenco(and again Michael Tafoya)",
            "Pop Latino",
            "Portuguese fado(and again Sandra Sanders)",
            "Raíces",
            "Reggaeton y Hip-Hop",
            "Regional Mexicano",
            "Salsa y Tropical",
            "New Age",
            "Environmental",
            "Healing",
            "Meditation",
            "Nature",
            "Relaxation",
            "Travel",
            "Opera",
            "Pop",
            "Adult Contemporary",
            "Britpop",
            "Bubblegum Pop(thx Haug & John Maher)",
            "Chamber Pop(thx Haug)",
            "Dance Pop",
            "Dream Pop(thx Haug)",
            "Electro Pop(thx Haug)",
            "Orchestral Pop(thx Haug)",
            "Pop/Rock",
            "Power Pop(thx Haug)",
            "Soft Rock",
            "Synthpop(thx Haug)",
            "Teen Pop",
            "R&B/Soul",
            "Contemporary R&B",
            "Disco(not a top level genre Sheldon Reynolds!)",
            "Doo Wop",
            "Funk",
            "Modern Soul(Cheers Nik)",
            "Motown",
            "Neo-Soul",
            "Northern Soul(Cheers Nik & John Maher)",
            "Psychedelic Soul(thank you John Maher)",
            "Quiet Storm",
            "Soul",
            "Soul Blues(Cheers Nik)",
            "Southern Soul(Cheers Nik)",
            "Reggae",
            "Dancehall",
            "Dub",
            "Roots Reggae",
            "Ska",
            "Rock",
            "Acid Rock(with thanks to Alex Antonio)",
            "Adult-Oriented Rock(thanks to John Maher)",
            "Afro Punk",
            "Adult Alternative",
            "Alternative Rock(thx Caleb Browning)",
            "American Trad Rock",
            "Anatolian Rock",
            "Arena Rock",
            "Art Rock",
            "Blues-Rock",
            "British Invasion",
            "Death Metal / Black Metal",
            "Glam Rock",
            "Gothic Metal(fits here Sam DeRenzis – thx)",
            "Hair Metal",
            "Hard Rock",
            "Metal",
            "Noise Rock(genre – Japanoise – thx Dominik Landahl)",
            "Jam Bands",
            "Post Punk(thx Ben Vee Bedlamite)",
            "Prog-Rock/Art Rock",
            "Psychedelic",
            "Rock & Roll",
            "Rockabilly(it’s here Mark Murdock!)",
            "Roots Rock",
            "Singer/Songwriter",
            "Southern Rock",
            "Surf",
            "Tex-Mex",
            "Time Lord Rock(Trock) ~ (thanks to ‘Melia G)",
            "Singer/Songwriter",
            "Alternative Folk",
            "Contemporary Folk",
            "Contemporary Singer/Songwriter",
            "Indie Folk(with thanks to Andrew Barrett)",
            "Folk-Rock",
            "Love Song(Chanson – merci Marcel Borchert)",
            "New Acoustic",
            "Traditional Folk",
            "Soundtrack",
            "Foreign Cinema",
            "Musicals",
            "Original Score",
            "Soundtrack",
            "TV Soundtrack",
            "Spoken Word",
            "Tex-Mex / Tejano(with thx to Israel Lopez)",
            "Chicano",
            "Classic",
            "Conjunto",
            "Conjunto Progressive",
            "New Mex",
            "Tex-Mex",
            "Vocal",
            "A cappella(with kudos to Sheldon Reynolds)",
            "Barbershop(with thx to Kelly Chism)",
            "Doo-wop(with thx to Bradley Thompson)",
            "Gregorian Chant(hat tip to Deborah Knight-Nikifortchuk)",
            "Standards",
            "Traditional Pop",
            "Vocal Jazz",
            "Vocal Pop",
            "World",
            "Africa",
            "Afro-Beat",
            "Afro-Pop",
            "Asia",
            "Australia",
            "Cajun",
            "Calypso(thx Gerald John)",
            "Caribbean",
            "Celtic",
            "Celtic Folk",
            "Contemporary Celtic",
            "Dangdut(thank you Achmad Ivanny)",
            "Drinking Songs",
            "Drone(with thx to Robert Conrod)",
            "Europe",
            "France",
            "Hawaii",
            "Indian Ghazal(thank you Gitika Thakur)",
            "Indian Pop",
            "Japan",
            "Japanese Pop",
            "Klezmer",
            "Middle East",
            "North America",
            "Ode(thank you Sheldon Reynolds)",
            "Polka",
            "Soca(thx Gerald John)",
            "South Africa",
            "South America",
            "Traditional Celtic",
            "Worldbeat",
            "Zydeco"
        };
    }
}
